@echo off
echo 🔄 Redémarrage complet avec nettoyage...

echo 📦 Arrêt du serveur...
taskkill /f /im node.exe 2>nul

echo 🗑️ Nettoyage des caches...
if exist .next rmdir /s /q .next 2>nul
if exist node_modules\.cache rmdir /s /q node_modules\.cache 2>nul

echo ⏳ Attente de 3 secondes...
timeout /t 3 /nobreak >nul

echo 🚀 Redémarrage du serveur...
npm run dev